### ISSUE TITLE
Crash on Server Startup - java.lang.NoClassDefFoundError: net/minecraft/client/renderer/ItemMeshDefinition

### ISSUE THREAD

**Issue by rckymtnrfc** [Vanhal/Contraptions#1]
I'm seeing the following crash when starting up the server with this mod added.

http://pastebin.com/6B133G65

Thanks!

**Comment by Vanhal** [comment]
Ah yes... I probably should have actually tested it on a server.

**Comment by rckymtnrfc** [comment]
I always seem to find the server crashes since I prefer to run a server and offload some of the processing my PC has to do while I play.   =)

**Comment by Vanhal** [comment]
Should be fixed in newest version. There is some other sync issues that I have to deal with, but the mod should be usable at least.

**Comment by rckymtnrfc** [comment]
Thanks for the quick fix.  Looking forward to checking this out once I get off work.
